package main


import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/go-redis/redis/v8"
	_ "github.com/lib/pq"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// ─── Global
variables ────────────────────────────────────────────────────────

var (
	db          *sql.DB
	redisClient *redis.Client
	ctx         = context.Background()

	requestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lendfast_reporting_requests_total",
			Help: "Total requests to Reporting Service",
		},
		[]string{"method", "endpoint", "status"},
	)
	requestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name: "lendfast_reporting_request_duration_seconds",
			Help:    "Request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "endpoint"},
	)
	reportsGenerated = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lendfast_reports_generated_total",
			Help: "Total reports generated by type",
		},
		[]string{"report_type"},
	)
	reportLatency = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name: "lendfast_report_generation_seconds",
			Help:    "Report generation latency in seconds",
			Buckets: []float64{0.1, 0.25, 0.5, 1, 2.5, 5, 10},
		},
		[]string{"report_type"},
	)
)

func init() {
	prometheus.MustRegister(requestsTotal)
	prometheus.MustRegister(requestDuration)
	prometheus.MustRegister(reportsGenerated)
	prometheus.MustRegister(reportLatency)
}

// ─── Response Models ─────────────────────────────────────────────────────────

type PortfolioReport struct {
	GeneratedAt      string            `json:"generated_at"`
	TotalLoans       int               `json:"total_loans"`
	ActiveLoans      int               `json:"active_loans"`
	TotalDisbursed   float64           `json:"total_disbursed"`
	TotalOutstanding float64           `json:"total_outstanding"`
	AverageRate      float64           `json:"average_interest_rate"`
	ByStatus         []StatusBreakdown `json:"by_status"`
	ByLoanType       []TypeBreakdown   `json:"by_loan_type"`
	MonthlyTrend     []MonthlyMetric   `json:"monthly_trend"`
}

type StatusBreakdown struct {
	Status string  `json:"status"`
	Count  int     `json:"count"`
	Amount float64 `json:"amount"`
}

type TypeBreakdown struct {
	LoanType string  `json:"loan_type"`
	Count    int     `json:"count"`
	Amount   float64 `json:"amount"`
	AvgRate  float64 `json:"avg_rate"`
}

type MonthlyMetric struct {
	Month       string  `json:"month"`
	Disbursed   float64 `json:"disbursed"`
	Collections float64 `json:"collections"`
	NewLoans    int     `json:"new_loans"`
}

type DelinquencyReport struct {
	GeneratedAt      string            `json:"generated_at"`
	TotalDelinquent  int               `json:"total_delinquent"`
	TotalOverdue     float64           `json:"total_overdue"`
	DelinquencyRate  float64           `json:"delinquency_rate_pct"`
	ByLevel          []LevelBreakdown  `json:"by_escalation_level"`
	ByAgingBucket    []AgingBucket     `json:"by_aging_bucket"`
	TopDelinquencies []DelinquencyItem `json:"top_delinquencies"`
}

type LevelBreakdown struct {
	Level  string  `json:"level"`
	Count  int     `json:"count"`
	Amount float64 `json:"amount"`
}

type AgingBucket struct {
	Bucket string  `json:"bucket"`
	Count  int     `json:"count"`
	Amount float64 `json:"amount"`
}

type DelinquencyItem struct {
	DelinquencyID string  `json:"delinquency_id"`
	LoanID        string  `json:"loan_id"`
	BorrowerID    string  `json:"borrower_id"`
	DaysPastDue   int     `json:"days_past_due"`
	AmountOverdue float64 `json:"amount_overdue"`
	Level         string  `json:"escalation_level"`
}

type RevenueReport struct {
	GeneratedAt     string          `json:"generated_at"`
	Period          string          `json:"period"`
	TotalRevenue    float64         `json:"total_revenue"`
	InterestIncome  float64         `json:"interest_income"`
	FeeIncome       float64         `json:"fee_income"`
	PrincipalRepaid float64         `json:"principal_repaid"`
	MonthlyRevenue  []MonthRevenue  `json:"monthly_revenue"`
	ByPaymentMethod []MethodRevenue `json:"by_payment_method"`
}

type MonthRevenue struct {
	Month           string  `json:"month"`
	InterestIncome  float64 `json:"interest_income"`
	FeeIncome       float64 `json:"fee_income"`
	PrincipalRepaid float64 `json:"principal_repaid"`
	TotalPayments   int     `json:"total_payments"`
}

type MethodRevenue struct {
	Method string  `json:"method"`
	Count  int     `json:"count"`
	Amount float64 `json:"amount"`
}

type DashboardReport struct {
	GeneratedAt         string     `json:"generated_at"`
	Overview            Overview   `json:"overview"`
	ApplicationPipeline Pipeline   `json:"application_pipeline"`
	RecentActivity      []Activity `json:"recent_activity"`
	Alerts              []Alert    `json:"alerts"`
}

type Overview struct {
	TotalBorrowers    int     `json:"total_borrowers"`
	ActiveBorrowers   int     `json:"active_borrowers"`
	TotalApplications int     `json:"total_applications"`
	PendingApps       int     `json:"pending_applications"`
	ActiveLoans       int     `json:"active_loans"`
	TotalOutstanding  float64 `json:"total_outstanding"`
	DelinquencyRate   float64 `json:"delinquency_rate_pct"`
	AvgCreditScore    float64 `json:"avg_credit_score"`
}

type Pipeline struct {
	Draft       int `json:"draft"`
	Submitted   int `json:"submitted"`
	UnderReview int `json:"under_review"`
	Approved    int `json:"approved"`
	Rejected    int `json:"rejected"`
	Disbursed   int `json:"disbursed"`
}

type Activity struct {
	Type      string `json:"type"`
	Detail    string `json:"detail"`
	Timestamp string `json:"timestamp"`
}

type Alert struct {
	Severity string `json:"severity"`
	Message  string `json:"message"`
}

// ─── Main ────────────────────────────────────────────────────────────────────

func main() {
	log.Println("🚀 LendFast Reporting Service starting...")

	// Database
	var err error
	dbURL := getEnv("DATABASE_URL", "postgres://fintech:fintech123@payflow-postgres:5432/lendfast?sslmode=disable")
	db, err = sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	defer db.Close()

	db.SetMaxOpenConns(25)
	db.SetMaxIdleConns(10)
	db.SetConnMaxLifetime(5 * time.Minute)

	if err = db.Ping(); err != nil {
		log.Println("⚠ Database not available:", err)
	} else {
		log.Println("✓ Database connected")
	}

	// Redis (for caching reports)
	redisClient = redis.NewClient(&redis.Options{
		Addr:     getEnv("REDIS_URL", "payflow-redis:6379"),
		Password: "",
		DB:       3,
	})
	if err := redisClient.Ping(ctx).Err(); err != nil {
		log.Println("⚠ Redis not available:", err)
	} else {
		log.Println("✓ Redis connected")
	}

	// Gin - with request logging
	gin.SetMode(gin.ReleaseMode)
	router := gin.Default()
	router.Use(prometheusMiddleware())

	// Health & metrics
	router.GET("/health", healthCheck)
	router.GET("/metrics", gin.WrapH(promhttp.Handler()))
	router.GET("/api/v1/ping",
func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"message": "pong", "service": "reporting-service"})
	})

	// Report routes
	v1 := router.Group("/api/v1")
	{
		v1.GET("/reports/portfolio", portfolioReport)
		v1.GET("/reports/delinquency", delinquencyReport)
		v1.GET("/reports/revenue", revenueReport)
		v1.GET("/reports/dashboard", dashboardReport)
		v1.GET("/reports/borrower/:borrower_id", borrowerReport)
		v1.GET("/reports/loan/:loan_id", loanDetailReport)
		v1.GET("/reports/cohort", cohortAnalysis)
	}

	// Start server
	port := getEnv("PORT", "8307")
	srv := &http.Server{
		Addr:         ":" + port,
		Handler:      router,
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  120 * time.Second,
	}

	go
func() {
		log.Printf("🚀 Reporting Service running on port %s\n", port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server error: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down Reporting Service...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Fatal("Server forced to shutdown:", err)
	}
	log.Println("Reporting Service exited")
}

// ─── Report Handlers ─────────────────────────────────────────────────────────

func portfolioReport(c *gin.Context) {
	start := time.Now()
	cacheKey := "report:portfolio"

	// Check Redis cache
	if cached, err := redisClient.Get(ctx, cacheKey).Result(); err == nil {
		c.Data(http.StatusOK, "application/json", []byte(cached))
		return
	}

	report := PortfolioReport{
		GeneratedAt: time.Now().Format(time.RFC3339),
	}

	// Total counts and amounts
	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(principal_amount), 0), COALESCE(AVG(interest_rate), 0) FROM loans`).Scan(
		&report.TotalLoans, &report.TotalDisbursed, &report.AverageRate)

	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(remaining_balance), 0) FROM loans WHERE status = 'active'`).Scan(
		&report.ActiveLoans, &report.TotalOutstanding)

	// By status
	rows, err := db.Query(`
		SELECT status, COUNT(*), COALESCE(SUM(principal_amount), 0)
		FROM loans GROUP BY status ORDER BY COUNT(*) DESC`)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var sb StatusBreakdown
			rows.Scan(&sb.Status, &sb.Count, &sb.Amount)
			report.ByStatus = append(report.ByStatus, sb)
		}
	}

	// By loan type
	rows2, err := db.Query(`
		SELECT loan_type, COUNT(*), COALESCE(SUM(principal_amount), 0), COALESCE(AVG(interest_rate), 0)
		FROM loans GROUP BY loan_type ORDER BY SUM(principal_amount) DESC`)
	if err == nil {
		defer rows2.Close()
		for rows2.Next() {
			var tb TypeBreakdown
			rows2.Scan(&tb.LoanType, &tb.Count, &tb.Amount, &tb.AvgRate)
			report.ByLoanType = append(report.ByLoanType, tb)
		}
	}

	// Monthly trend (last 12 months)
	rows3, err := db.Query(`
		SELECT TO_CHAR(created_at, 'YYYY-MM') AS month,
			COALESCE(SUM(principal_amount), 0) AS disbursed,
			COUNT(*) AS new_loans
		FROM loans
		WHERE created_at >= NOW() - INTERVAL '12 months'
		GROUP BY TO_CHAR(created_at, 'YYYY-MM')
		ORDER BY month`)
	if err == nil {
		defer rows3.Close()
		for rows3.Next() {
			var mm MonthlyMetric
			var newLoans int
			rows3.Scan(&mm.Month, &mm.Disbursed, &newLoans)
			mm.NewLoans = newLoans
			report.MonthlyTrend = append(report.MonthlyTrend, mm)
		}
	}

	// Cache for 5 minutes
	cacheReport(cacheKey, report)

	reportsGenerated.WithLabelValues("portfolio").Inc()
	reportLatency.WithLabelValues("portfolio").Observe(time.Since(start).Seconds())

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func delinquencyReport(c *gin.Context) {
	start := time.Now()
	cacheKey := "report:delinquency"

	if cached, err := redisClient.Get(ctx, cacheKey).Result(); err == nil {
		c.Data(http.StatusOK, "application/json", []byte(cached))
		return
	}

	report := DelinquencyReport{
		GeneratedAt: time.Now().Format(time.RFC3339),
	}

	// Total delinquent
	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(amount_overdue), 0) FROM delinquencies WHERE status = 'open'`).Scan(
		&report.TotalDelinquent, &report.TotalOverdue)

	// Delinquency rate
	var activeLoans int
	db.QueryRow(`SELECT COUNT(*) FROM loans WHERE status = 'active'`).Scan(&activeLoans)
	if activeLoans > 0 {
		report.DelinquencyRate = float64(report.TotalDelinquent) / float64(activeLoans) * 100
	}

	// By escalation level
	rows, err := db.Query(`
		SELECT escalation_level, COUNT(*), COALESCE(SUM(amount_overdue), 0)
		FROM delinquencies WHERE status = 'open'
		GROUP BY escalation_level
		ORDER BY CASE escalation_level WHEN 'legal' THEN 4 WHEN 'collections' THEN 3 WHEN 'warning' THEN 2 ELSE 1 END DESC`)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var lb LevelBreakdown
			rows.Scan(&lb.Level, &lb.Count, &lb.Amount)
			report.ByLevel = append(report.ByLevel, lb)
		}
	}

	// By aging bucket
	agingQuery := `
		SELECT
			CASE
				WHEN days_past_due <= 30 THEN '1-30 days'
				WHEN days_past_due <= 60 THEN '31-60 days'
				WHEN days_past_due <= 90 THEN '61-90 days'
				ELSE '90+ days'
			END AS bucket,
			COUNT(*), COALESCE(SUM(amount_overdue), 0)
		FROM delinquencies WHERE status = 'open'
		GROUP BY bucket
		ORDER BY MIN(days_past_due)`
	rows2, err := db.Query(agingQuery)
	if err == nil {
		defer rows2.Close()
		for rows2.Next() {
			var ab AgingBucket
			rows2.Scan(&ab.Bucket, &ab.Count, &ab.Amount)
			report.ByAgingBucket = append(report.ByAgingBucket, ab)
		}
	}

	// Top 10 delinquencies
	rows3, err := db.Query(`
		SELECT delinquency_id, loan_id, borrower_id, days_past_due, amount_overdue, escalation_level
		FROM delinquencies WHERE status = 'open'
		ORDER BY amount_overdue DESC LIMIT 10`)
	if err == nil {
		defer rows3.Close()
		for rows3.Next() {
			var di DelinquencyItem
			rows3.Scan(&di.DelinquencyID, &di.LoanID, &di.BorrowerID, &di.DaysPastDue, &di.AmountOverdue, &di.Level)
			report.TopDelinquencies = append(report.TopDelinquencies, di)
		}
	}

	cacheReport(cacheKey, report)
	reportsGenerated.WithLabelValues("delinquency").Inc()
	reportLatency.WithLabelValues("delinquency").Observe(time.Since(start).Seconds())

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func revenueReport(c *gin.Context) {
	start := time.Now()
	period := c.DefaultQuery("period", "12")
	cacheKey := fmt.Sprintf("report:revenue:%s", period)

	if cached, err := redisClient.Get(ctx, cacheKey).Result(); err == nil {
		c.Data(http.StatusOK, "application/json", []byte(cached))
		return
	}

	report := RevenueReport{
		GeneratedAt: time.Now().Format(time.RFC3339),
		Period:      period + " months",
	}

	// Total revenue from payments
	db.QueryRow(`
		SELECT COALESCE(SUM(interest_portion), 0), COALESCE(SUM(late_fee), 0), COALESCE(SUM(principal_portion), 0)
		FROM payments WHERE status = 'completed' AND created_at >= NOW() - ($1 || ' months')::INTERVAL`, period,
	).Scan(&report.InterestIncome, &report.FeeIncome, &report.PrincipalRepaid)
	report.TotalRevenue = report.InterestIncome + report.FeeIncome

	// Monthly revenue
	rows, err := db.Query(`
		SELECT TO_CHAR(created_at, 'YYYY-MM') AS month,
			COALESCE(SUM(interest_portion), 0) AS interest,
			COALESCE(SUM(late_fee), 0) AS fees,
			COALESCE(SUM(principal_portion), 0) AS principal,
			COUNT(*) AS payment_count
		FROM payments
		WHERE status = 'completed' AND created_at >= NOW() - ($1 || ' months')::INTERVAL
		GROUP BY TO_CHAR(created_at, 'YYYY-MM')
		ORDER BY month`, period)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var mr MonthRevenue
			rows.Scan(&mr.Month, &mr.InterestIncome, &mr.FeeIncome, &mr.PrincipalRepaid, &mr.TotalPayments)
			report.MonthlyRevenue = append(report.MonthlyRevenue, mr)
		}
	}

	// By payment method
	rows2, err := db.Query(`
		SELECT payment_method, COUNT(*), COALESCE(SUM(amount), 0)
		FROM payments
		WHERE status = 'completed' AND created_at >= NOW() - ($1 || ' months')::INTERVAL
		GROUP BY payment_method ORDER BY SUM(amount) DESC`, period)
	if err == nil {
		defer rows2.Close()
		for rows2.Next() {
			var mr MethodRevenue
			rows2.Scan(&mr.Method, &mr.Count, &mr.Amount)
			report.ByPaymentMethod = append(report.ByPaymentMethod, mr)
		}
	}

	cacheReport(cacheKey, report)
	reportsGenerated.WithLabelValues("revenue").Inc()
	reportLatency.WithLabelValues("revenue").Observe(time.Since(start).Seconds())

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func dashboardReport(c *gin.Context) {
	start := time.Now()
	cacheKey := "report:dashboard"

	if cached, err := redisClient.Get(ctx, cacheKey).Result(); err == nil {
		c.Data(http.StatusOK, "application/json", []byte(cached))
		return
	}

	report := DashboardReport{
		GeneratedAt: time.Now().Format(time.RFC3339),
	}

	// Overview
	db.QueryRow(`SELECT COUNT(*) FROM borrowers`).Scan(&report.Overview.TotalBorrowers)
	db.QueryRow(`SELECT COUNT(*) FROM borrowers WHERE status = 'active'`).Scan(&report.Overview.ActiveBorrowers)
	db.QueryRow(`SELECT COUNT(*) FROM applications`).Scan(&report.Overview.TotalApplications)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status IN ('submitted', 'under_review')`).Scan(&report.Overview.PendingApps)
	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(remaining_balance), 0) FROM loans WHERE status = 'active'`).Scan(
		&report.Overview.ActiveLoans, &report.Overview.TotalOutstanding)
	db.QueryRow(`SELECT COALESCE(AVG(credit_score), 0) FROM borrowers WHERE credit_score > 0`).Scan(&report.Overview.AvgCreditScore)

	// Delinquency rate
	var delinquent int
	db.QueryRow(`SELECT COUNT(*) FROM delinquencies WHERE status = 'open'`).Scan(&delinquent)
	if report.Overview.ActiveLoans > 0 {
		report.Overview.DelinquencyRate = float64(delinquent) / float64(report.Overview.ActiveLoans) * 100
	}

	// Application pipeline
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'draft'`).Scan(&report.ApplicationPipeline.Draft)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'submitted'`).Scan(&report.ApplicationPipeline.Submitted)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'under_review'`).Scan(&report.ApplicationPipeline.UnderReview)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'approved'`).Scan(&report.ApplicationPipeline.Approved)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'rejected'`).Scan(&report.ApplicationPipeline.Rejected)
	db.QueryRow(`SELECT COUNT(*) FROM applications WHERE status = 'disbursed'`).Scan(&report.ApplicationPipeline.Disbursed)

	// Recent activity (last 10 items)
	rows, err := db.Query(`
		(SELECT 'loan_created' AS type, CONCAT('New loan ', loan_id, ' - $', principal_amount) AS detail, created_at
		 FROM loans ORDER BY created_at DESC LIMIT 3)
		UNION ALL
		(SELECT 'payment' AS type, CONCAT('Payment of $', amount, ' on ', loan_id) AS detail, created_at
		 FROM payments WHERE status = 'completed' ORDER BY created_at DESC LIMIT 3)
		UNION ALL
		(SELECT 'application' AS type, CONCAT('Application ', application_id, ' - ', status) AS detail, created_at
		 FROM applications ORDER BY created_at DESC LIMIT 4)
		ORDER BY created_at DESC LIMIT 10`)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var a Activity
			var ts time.Time
			rows.Scan(&a.Type, &a.Detail, &ts)
			a.Timestamp = ts.Format(time.RFC3339)
			report.RecentActivity = append(report.RecentActivity, a)
		}
	}

	// Alerts
	report.Alerts = generateAlerts(delinquent, report.Overview.PendingApps)

	cacheReport(cacheKey, report)
	reportsGenerated.WithLabelValues("dashboard").Inc()
	reportLatency.WithLabelValues("dashboard").Observe(time.Since(start).Seconds())

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func borrowerReport(c *gin.Context) {
	borrowerID := c.Param("borrower_id")

	type BorrowerDetail struct {
		BorrowerID       string  `json:"borrower_id"`
		Name             string  `json:"name"`
		Email            string  `json:"email"`
		CreditScore      int     `json:"credit_score"`
		Status           string  `json:"status"`
		TotalLoans       int     `json:"total_loans"`
		ActiveLoans      int     `json:"active_loans"`
		TotalBorrowed    float64 `json:"total_borrowed"`
		TotalOutstanding float64 `json:"total_outstanding"`
		TotalPaid        float64 `json:"total_paid"`
		Delinquencies    int     `json:"open_delinquencies"`
		OnTimeRate       float64 `json:"on_time_payment_rate_pct"`
	}

	var report BorrowerDetail
	report.BorrowerID = borrowerID

	// Borrower info
	err := db.QueryRow(`
		SELECT CONCAT(first_name, ' ', last_name), email, credit_score, status 
		FROM borrowers WHERE borrower_id = $1`, borrowerID,
	).Scan(&report.Name, &report.Email, &report.CreditScore, &report.Status)
	if err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, gin.H{"error": "Borrower not found"})
		return
	}

	// Loan stats
	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(principal_amount), 0) FROM loans WHERE borrower_id = $1`, borrowerID).Scan(
		&report.TotalLoans, &report.TotalBorrowed)
	db.QueryRow(`SELECT COUNT(*), COALESCE(SUM(remaining_balance), 0) FROM loans WHERE borrower_id = $1 AND status = 'active'`, borrowerID).Scan(
		&report.ActiveLoans, &report.TotalOutstanding)

	// Payment stats
	db.QueryRow(`SELECT COALESCE(SUM(amount), 0) FROM payments WHERE loan_id IN (SELECT loan_id FROM loans WHERE borrower_id = $1) AND status = 'completed'`, borrowerID).Scan(
		&report.TotalPaid)

	// Delinquencies
	db.QueryRow(`SELECT COUNT(*) FROM delinquencies WHERE borrower_id = $1 AND status = 'open'`, borrowerID).Scan(&report.Delinquencies)

	// On-time rate
	var totalInstallments, paidOnTime int
	db.QueryRow(`SELECT COUNT(*) FROM repayment_schedule WHERE loan_id IN (SELECT loan_id FROM loans WHERE borrower_id = $1)`, borrowerID).Scan(&totalInstallments)
	db.QueryRow(`SELECT COUNT(*) FROM repayment_schedule WHERE loan_id IN (SELECT loan_id FROM loans WHERE borrower_id = $1) AND status = 'paid' AND paid_date <= due_date`, borrowerID).Scan(&paidOnTime)
	if totalInstallments > 0 {
		report.OnTimeRate = float64(paidOnTime) / float64(totalInstallments) * 100
	}

	reportsGenerated.WithLabelValues("borrower").Inc()

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func loanDetailReport(c *gin.Context) {
	loanID := c.Param("loan_id")

	type LoanDetail struct {
		LoanID            string  `json:"loan_id"`
		BorrowerID        string  `json:"borrower_id"`
		LoanType          string  `json:"loan_type"`
		PrincipalAmount   float64 `json:"principal_amount"`
		InterestRate      float64 `json:"interest_rate"`
		TermMonths        int     `json:"term_months"`
		EMI               float64 `json:"emi_amount"`
		Status            string  `json:"status"`
		RemainingBalance  float64 `json:"remaining_balance"`
		TotalPaid         float64 `json:"total_paid"`
		PrincipalPaid     float64 `json:"principal_paid"`
		InterestPaid      float64 `json:"interest_paid"`
		LateFees          float64 `json:"late_fees_charged"`
		NextDueDate       *string `json:"next_due_date,omitempty"`
		NextDueAmount     float64 `json:"next_due_amount"`
		PaidInstallments  int     `json:"paid_installments"`
		TotalInstallments int     `json:"total_installments"`
		CompletionPct     float64 `json:"completion_pct"`
		IsDelinquent      bool    `json:"is_delinquent"`
	}

	var report LoanDetail
	err := db.QueryRow(`
		SELECT loan_id, borrower_id, loan_type, principal_amount, interest_rate, term_months, emi_amount, status, remaining_balance
		FROM loans WHERE loan_id = $1`, loanID,
	).Scan(&report.LoanID, &report.BorrowerID, &report.LoanType, &report.PrincipalAmount,
		&report.InterestRate, &report.TermMonths, &report.EMI, &report.Status, &report.RemainingBalance)

	if err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, gin.H{"error": "Loan not found"})
		return
	}

	// Payment totals
	db.QueryRow(`
		SELECT COALESCE(SUM(amount), 0), COALESCE(SUM(principal_portion), 0), COALESCE(SUM(interest_portion), 0), COALESCE(SUM(late_fee), 0)
		FROM payments WHERE loan_id = $1 AND status = 'completed'`, loanID,
	).Scan(&report.TotalPaid, &report.PrincipalPaid, &report.InterestPaid, &report.LateFees)

	// Installment info
	db.QueryRow(`SELECT COUNT(*) FROM repayment_schedule WHERE loan_id = $1`, loanID).Scan(&report.TotalInstallments)
	db.QueryRow(`SELECT COUNT(*) FROM repayment_schedule WHERE loan_id = $1 AND status = 'paid'`, loanID).Scan(&report.PaidInstallments)

	if report.TotalInstallments > 0 {
		report.CompletionPct = float64(report.PaidInstallments) / float64(report.TotalInstallments) * 100
	}

	// Next due
	var nextDate time.Time
	err = db.QueryRow(`
		SELECT due_date, total_amount FROM repayment_schedule
		WHERE loan_id = $1 AND status = 'pending'
		ORDER BY due_date ASC LIMIT 1`, loanID,
	).Scan(&nextDate, &report.NextDueAmount)
	if err == nil {
		formatted := nextDate.Format("2006-01-02")
		report.NextDueDate = &formatted
	}

	// Delinquency check
	var delCount int
	db.QueryRow(`SELECT COUNT(*) FROM delinquencies WHERE loan_id = $1 AND status = 'open'`, loanID).Scan(&delCount)
	report.IsDelinquent = delCount > 0

	reportsGenerated.WithLabelValues("loan_detail").Inc()

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": report})
}

func cohortAnalysis(c *gin.Context) {
	start := time.Now()
	cacheKey := "report:cohort"

	if cached, err := redisClient.Get(ctx, cacheKey).Result(); err == nil {
		c.Data(http.StatusOK, "application/json", []byte(cached))
		return
	}

	type Cohort struct {
		Month           string  `json:"origination_month"`
		LoansOriginated int     `json:"loans_originated"`
		TotalAmount     float64 `json:"total_amount"`
		Active          int     `json:"active"`
		PaidOff         int     `json:"paid_off"`
		Defaulted       int     `json:"defaulted"`
		DefaultRate     float64 `json:"default_rate_pct"`
		AvgCreditScore  float64 `json:"avg_credit_score"`
	}

	rows, err := db.Query(`
		SELECT
			TO_CHAR(l.created_at, 'YYYY-MM') AS cohort_month,
			COUNT(*) AS originated,
			COALESCE(SUM(l.principal_amount), 0) AS total_amount,
			COUNT(*) FILTER (WHERE l.status = 'active') AS active,
			COUNT(*) FILTER (WHERE l.status = 'paid_off') AS paid_off,
			COUNT(*) FILTER (WHERE l.status = 'defaulted') AS defaulted,
			COALESCE(AVG(b.credit_score), 0) AS avg_score
		FROM loans l
		LEFT JOIN borrowers b ON l.borrower_id = b.borrower_id
		WHERE l.created_at >= NOW() - INTERVAL '12 months'
		GROUP BY TO_CHAR(l.created_at, 'YYYY-MM')
		ORDER BY cohort_month`)

	cohorts := []Cohort{}
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var co Cohort
			rows.Scan(&co.Month, &co.LoansOriginated, &co.TotalAmount, &co.Active, &co.PaidOff, &co.Defaulted, &co.AvgCreditScore)
			if co.LoansOriginated > 0 {
				co.DefaultRate = float64(co.Defaulted) / float64(co.LoansOriginated) * 100
			}
			cohorts = append(cohorts, co)
		}
	}

	result := gin.H{
		"generated_at":  time.Now().Format(time.RFC3339),
		"cohorts":       cohorts,
		"total_cohorts": len(cohorts),
	}

	cacheReport(cacheKey, result)
	reportsGenerated.WithLabelValues("cohort").Inc()
	reportLatency.WithLabelValues("cohort").Observe(time.Since(start).Seconds())

	c.JSON(http.StatusOK, gin.H{"status": "success", "data": result})
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

func generateAlerts(delinquent, pendingApps int) []Alert {
	alerts := []Alert{}

	if delinquent > 10 {
		alerts = append(alerts, Alert{
			Severity: "critical",
			Message:  fmt.Sprintf("High delinquency count: %d open delinquencies", delinquent),
		})
	} else if delinquent > 5 {
		alerts = append(alerts, Alert{
			Severity: "warning",
			Message:  fmt.Sprintf("Elevated delinquency count: %d open delinquencies", delinquent),
		})
	}

	if pendingApps > 20 {
		alerts = append(alerts, Alert{
			Severity: "warning",
			Message:  fmt.Sprintf("Application backlog: %d applications pending review", pendingApps),
		})
	}

	// Check for legal-level delinquencies
	var legalCount int
	if db != nil {
		db.QueryRow(`SELECT COUNT(*) FROM delinquencies WHERE escalation_level = 'legal' AND status = 'open'`).Scan(&legalCount)
	}
	if legalCount > 0 {
		alerts = append(alerts, Alert{
			Severity: "critical",
			Message:  fmt.Sprintf("%d delinquencies at legal escalation level", legalCount),
		})
	}

	if len(alerts) == 0 {
		alerts = append(alerts, Alert{
			Severity: "info",
			Message:  "All metrics within normal ranges",
		})
	}

	return alerts
}

func cacheReport(key string, data interface{}) {
	if redisClient == nil {
		return
	}
	bytes, err := json.Marshal(data)
	if err == nil {
		redisClient.Set(ctx, key, bytes, 5*time.Minute)
	}
}

func healthCheck(c *gin.Context) {
	health := gin.H{
		"status":  "UP",
		"service": "lendfast-reporting-service",
		"port":    "8307",
		"time":    time.Now().Format(time.RFC3339),
	}

	if db != nil {
		if err := db.Ping(); err != nil {
			health["database"] = "DOWN"
		} else {
			health["database"] = "UP"
		}
	}
	if err := redisClient.Ping(ctx).Err(); err != nil {
		health["redis"] = "DOWN"
	} else {
		health["redis"] = "UP"
	}

	c.JSON(http.StatusOK, health)
}

func prometheusMiddleware() gin.HandlerFunc {
	return
func(c *gin.Context) {
		start := time.Now()
		c.Next()
		duration := time.Since(start).Seconds()
		status := fmt.Sprintf("%d", c.Writer.Status())
		endpoint := c.FullPath()
		if endpoint == "" {
			endpoint = c.Request.URL.Path
		}
		requestsTotal.WithLabelValues(c.Request.Method, endpoint, status).Inc()
		requestDuration.WithLabelValues(c.Request.Method, endpoint).Observe(duration)
	}
}

func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

// Suppress unused import
var _ = strings.NewReader
